src/Entity/Auteur.php
<?php

namespace App\Entity;

use App\Repository\AuteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AuteurRepository::class)
 */
class Auteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateNaissance;

    /**
     * @ORM\ManyToOne(targetEntity=Nationalite::class, inversedBy="auteurs")
     */
    private $Nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Livre::class, mappedBy="auteurs")
     */
    private $livres;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getNationalite(): ?Nationalite
    {
        return $this->Nationalite;
    }

    public function setNationalite(?Nationalite $Nationalite): self
    {
        $this->Nationalite = $Nationalite;

        return $this;
    }

    /**
     * @return Collection<int, Livre>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livre $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->addAuteur($this);
        }

        return $this;
    }

    public function removeLivre(Livre $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            $livre->removeAuteur($this);
        }

        return $this;
    }
}

src/Controller/NewLivreController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Form\LivreType;
use App\Repository\LivreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
     * @Route("/new/livre", name="app_new_livre")
     */
class NewLivreController extends AbstractController
{
    #[Route('/', name: 'app_new_livre_index', methods: ['GET'])]
    public function index(LivreRepository $livreRepository): Response
    {
        return $this->render('new_livre/index.html.twig', [
            'livres' => $livreRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_new_livre_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LivreRepository $livreRepository): Response
    {
        $livre = new Livre();
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->save($livre, true);

            return $this->redirectToRoute('app_new_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('new_livre/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_new_livre_show', methods: ['GET'])]
    public function show(Livre $livre): Response
    {
        return $this->render('new_livre/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_new_livre_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        $form = $this->createForm(LivreType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $livreRepository->save($livre, true);

            return $this->redirectToRoute('app_new_livre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('new_livre/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_new_livre_delete', methods: ['POST'])]
    public function delete(Request $request, Livre $livre, LivreRepository $livreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $livreRepository->remove($livre, true);
        }

        return $this->redirectToRoute('app_new_livre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/new_livre/_delete_form.html.twig
<form method="post" action="{{ path('app_new_livre_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/new_livre/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/new_livre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livre{% endblock %}

{% block body %}
    <h1>Edit Livre</h1>

    {{ include('new_livre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_new_livre_index') }}">back to list</a>

    {{ include('new_livre/_delete_form.html.twig') }}
{% endblock %}

templates/new_livre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre index{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Livre index</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Quatrieme</th>
            <th>DateParution</th>
            <th>EmpruntPossible</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for livre in livres %}
            <tr>
                <td>{{ livre.id }}</td>
                <td>{{ livre.titre }}</td>
                <td>
                    {% for auteur in livre.auteurs %} <!-- Affichage des auteurs et de leur nationalité, séparés chacun par des virgules -->
                        {{ auteur.prenom }} {{ auteur.nom }} {{ auteur.nationalite.libelle}}{% if not loop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td>{{ livre.quatrieme }}</td>
                <td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
                <td>{{ livre.empruntPossible ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_new_livre_show', {'id': livre.id}) }}">show</a>
                    <a href="{{ path('app_new_livre_edit', {'id': livre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


    <a href="{{ path('app_new_livre_new') }}">Create new</a>
{% endblock %}

templates/new_livre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livre{% endblock %}

{% block body %}
    <h1>Create new Livre</h1>

    {{ include('new_livre/_form.html.twig') }}

    <a href="{{ path('app_new_livre_index') }}">back to list</a>
{% endblock %}

templates/new_livre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Livre</h1>

    <table>
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ livre.id }}</td>
        </tr>
        <tr>
            <th>Titre</th>
            <td>{{ livre.titre }}</td>
        </tr>
        <tr>
            <th>Quatrieme</th>
            <td>{{ livre.quatrieme }}</td>
        </tr>
        <tr>
            <th>DateParution</th>
            <td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>EmpruntPossible</th>
            <td>{{ livre.empruntPossible ? 'Yes' : 'No' }}</td>
        </tr>
        </tbody>
    </table>
</div>


    <a href="{{ path('app_new_livre_index') }}">back to list</a>

    <a href="{{ path('app_new_livre_edit', {'id': livre.id}) }}">edit</a>

    {{ include('new_livre/_delete_form.html.twig') }}
{% endblock %}